server:
  port: 3344

spring:
  application:
    name: micro-service-spring-cloud-config-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenzhongyu/micro-service-spring-cloud-config.git
