#server:
#  port: 7001
#
#eureka:
#  instance:
#    hostname: eureka7001.com
#  client:
#    register-with-eureka: false #表示不向注册中心注册自己
#    fetch-registry: false   #表示自己端就是注册中心，不需要去检索服务
#    service-url:
#      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/

spring:
  profiles:
    active: dev


---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: micro-service-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false   #表示自己端就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/

---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: micro-service-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false   #表示自己端就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/

