
server:
  port: 9527

spring:
  application:
    name: micro-service-cloud-zuul-gateway-9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
zuul:
  prefix: /bkb
  ignored-services: "*"
  routes:
    mydept.serviceId: micro-service-cloud-provider
    mydept.path: /mydept/**
