server:
  port: 80
  servlet:
    context-path: /consumer

spring:
  application:
    name: micro-service-cloud-consumer-80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: consumer80
    prefer-ip-address: true


info:
  tips: hello Spring cloud!!!